<Project>

  <Import Project="..\Directory.Build.props" />

  <PropertyGroup Label="Signing">
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)../key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' ">true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>tryAGI and contributors</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>nuget-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/tryAGI/OpusSharp</RepositoryUrl>
    <PackageProjectUrl>https://github.com/tryAGI/OpusSharp</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup Label="Nuget">
    <None Include="$(MSBuildThisFileDirectory)../../assets/nuget-icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)../../README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <PropertyGroup Label="Analyzers">
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Label="Versioning">
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerDefaultPreReleaseIdentifiers>dev</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>

  <ItemGroup Label="Versioning">
    <PackageReference Include="MinVer" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
